project:
  type: website

website:
  title: "DataViz@MQ"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: workshop.qmd
        text: Masterclass
      - href: contact.qmd
        text: Organisers & Contact
      - href: conduct.qmd
        text: Code of Conduct

format:
  html:
    theme:
      light: cerulean
      dark: darkly
    css: styles.css
    toc: true
margin-header: |
  ![DataViz@MQ Logo](logo.png)
body-header: | 
  This page brought to you by Thomas Fung & Iris Jiang of School of Mathematical & Physical Sciences at Macquarie University


