---
title: "Dashboard Masterclass 📚"
editor: 
  markdown: 
    wrap: 72
---

# Hello Quarto & Shiny Dashboard

Over two fully catered days on 25 & 26 September 2025, you'll dive into
hands-on masterclass to learn how to create dashboards with

-   Quarto (<https://quarto.org/docs/dashboards/>) and
-   Shiny (<https://shiny.posit.co>).

We assume you can already analyse and summarise your data in
computational notebooks with R and/or Python. This masterclass will then
enable you to share your insights or allow others to make their own
conclusions in visually appealing dashboards.

# Date & Location

|                                                              |
|--------------------------------------------------------------|
| 🗓️ 25 & 26 September, 2025                                   |
| 🕘 9am -- 5 pm                                               |
| 📍 14SCO Room 163  |

# Schedule

You can find the tentative schedule below. This is subject to change.

::: panel-tabset
## 25 Sep

|                |                                           |
|----------------|-------------------------------------------|
| 08:30 -- 09:00 | Registration                              |
| 09:00 -- 10:30 | Introduction to Dashboards                |
| 10:30 -- 11:00 | Coffee break ☕️️                           |
| 11:00 -- 12:30 | Dashboards Components                     |
| 12:30 -- 13:30 | Lunch 🍕🥤                                |
| 13:30 -- 15:00 | Theme and Styling                         |
| 15:00 -- 15:30 | Coffee break 🍵                           |
| 15:30 -- 17:00 | Parameters, Interactivity, and Deployment |

## 26 Sep

|                |                         |
|----------------|-------------------------|
| 08:00 -- 09:00 | Registration            |
| 09:00 -- 10:30 | Introduction to Shiny   |
| 10:30 -- 11:00 | Coffee break ☕️️         |
| 11:00 -- 12:30 | Reactive Programming    |
| 12:30 -- 13:30 | Lunch 🥤 🥪             |
| 13:30 -- 15:00 | Modern Uls with `bslib` |
| 15:00 -- 15:30 | Coffee break 🍵         |
| 15:30 -- 17:00 | Theming and Deploying   |
:::

# How to join

For catering purposes, please register to the masterclass when you
register for DataViz 2025:
<https://mqedu.qualtrics.com/jfe/form/SV_8IDFaeAnN29KLxI>.

Materials will be shared with participants on 24 Sep.

# Software & Setup

Prior to the masterclass, please check that you have the required
software and setup any accounts you might need for publishing your
dashboard!

::: panel-tabset
## 25 Sep

You will be able to follow along with this masterclass in `R` or in
`Python`.

Please see the required software suite for each language below.

### R

-   [R](https://cran.r-project.org): 4.5.1 or later

-   [Quarto](https://quarto.org/docs/download/): v1.8 or later

-   [RStudio](https://posit.co/download/rstudio-desktop/): 2025.05.1+513 or later

-   Packages:

```{r}
#| eval: false
# install.packages("pak")
pak::pak(c("tidyverse", "gt", "ggthemes", "DT", "here", "paletteer"))
```

### Python

-   [Python](https://www.python.org/downloads/): 3 or later
-   [Quarto](https://quarto.org/docs/download/): v1.8 or later
-   [VS Code](https://code.visualstudio.com/download) as well as the [VS
    Code Quarto
    Extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto)
    and [VS Code Jupyter
    Extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
-   Packages: We recommend `pip install`ing the following packages. If
    you have a different preferred way of managing your environment,
    you're welcomed to do so. Just make sure you have these packages
    installed in order to be able to follow along with the examples.

```         
great_tables==0.10.0
ipykernel==6.29.5
jupyter==1.0.0
pandas==2.2.2
plotnine==0.13.6
```

### Publishing accounts

You do not need to publish your dashboard during the workshop, but it
would be good practice!

To publish your website you'll need an account on one of Quarto's
publishing venues:

-   **(Recommended)** [Quarto Pub](https://quartopub.com/sign-up)
-   [GitHub](https://github.com) only **if you are already** a
    Git/GitHub user

## 26 Sep

TBD
:::